//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CLSilo;

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AccessPoint {
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    int _field3;
    int _field4;
    int _field5;
    double _field6;
    double _field7;
};

struct AssociationState {
    _Bool _field1;
    struct AccessPoint _field2;
};

struct AvailabilityTile;

struct BasicMutex {
    CDUnknownFunctionPointerType *_vptr$Mutex;
    struct MutexInfo *info;
};

struct Battery {
    double _field1;
    _Bool _field2;
    _Bool _field3;
    _Bool _field4;
};

struct CLAccessoryObserverListener {
    void *info;
    CDUnknownFunctionPointerType onConnected;
    CDUnknownFunctionPointerType onDisconnected;
    CDUnknownFunctionPointerType onNmeaReceived;
    CDUnknownFunctionPointerType onReferenceTime;
    CDUnknownFunctionPointerType onReferenceLocation;
    CDUnknownFunctionPointerType onEphemerisURL;
};

struct CLActivityAlarmConcentrator {
    struct BasicMutex _field1;
    struct set<CMActivityAlarm *, CLActivityAlarmConcentrator::AlarmCompare, std::__1::allocator<CMActivityAlarm *>> _field2[12];
};

struct CLApplicationLifecycleManager {
    id _field1;
    struct unique_ptr<CLAppMonitor_Type::Client, std::__1::default_delete<CLAppMonitor_Type::Client>> _field2;
    struct unique_ptr<CLDataProtectionManager_Type::Client, std::__1::default_delete<CLDataProtectionManager_Type::Client>> _field3;
    struct list<CLApplicationLifecycleManager::PendingLaunch, std::__1::allocator<CLApplicationLifecycleManager::PendingLaunch>> _field4;
    _Bool _field5;
};

struct CLBatchedLocations;

struct CLBundleLocationProvider {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    id _field4;
    id _field5;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> _field6;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> _field7;
    int _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    struct __CLClient *_field14;
    struct __CLClient *_field15;
    struct __CLClient *_field16;
    struct __CFString *_field17;
    struct __CFString *_field18;
};

struct CLCircularQueue<CLLocationHarvester::RealTimeHarvestInfo> {
    struct vector<CLLocationHarvester::RealTimeHarvestInfo, std::__1::allocator<CLLocationHarvester::RealTimeHarvestInfo>> _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
};

struct CLCollectionRequester {
    CDUnknownFunctionPointerType *_field1;
    CDUnknownFunctionPointerType *_field2;
    struct weak_ptr<CLCollectionRequester> _field3;
    id _field4;
    struct Listener {
        void *_field1;
        CDUnknownFunctionPointerType _field2;
        CDUnknownFunctionPointerType _field3;
        CDUnknownFunctionPointerType _field4;
    } _field5;
    id _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field10;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field11;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field12;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field13;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field14;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field15;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field16;
    _Bool _field17;
    CDStruct_f227fc05 _field18;
    CDStruct_f227fc05 _field19;
    id _field20;
    id _field21;
    id _field22;
    id _field23;
    id _field24;
    id _field25;
    id _field26;
    id _field27;
    id _field28;
    id _field29;
    id _field30;
    id _field31;
    id _field32;
    id _field33;
    id _field34;
    id _field35;
    id _field36;
    struct __CFString *_field37;
    struct __CFString *_field38;
    id _field39;
    int _field40;
};

struct CLCompassSessionStatsCollector;

struct CLConnection;

struct CLDaemonClient {
    struct DestructionAwareMutex _field1;
    id _field2;
    id _field3;
    struct Name _field4;
    struct __CFString *_field5;
    _Bool _field6;
    _Bool _field7;
    _Bool _field8;
    _Bool _field9;
    unsigned long long _field10;
    int _field11;
    _Bool _field12;
    id _field13;
    int _field14;
    struct list<std::__1::shared_ptr<CLConnectionMessage>, std::__1::allocator<std::__1::shared_ptr<CLConnectionMessage>>> _field15;
    struct set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>> _field16;
    unsigned long long _field17;
    struct map<std::__1::basic_string<char>, bool, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, bool>>> _field18;
    _Bool _field19;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field20;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field21;
    int _field22;
    _Bool _field23;
    id _field24;
    struct SBSProcessAssertion *_field25;
    int _field26;
    _Bool _field27;
    _Bool _field28;
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _field29;
    struct unique_ptr<CLFilteredLocationController_Type::Client, std::__1::default_delete<CLFilteredLocationController_Type::Client>> _field30;
    struct unique_ptr<CLSignificantChangeManager_Type::Client, std::__1::default_delete<CLSignificantChangeManager_Type::Client>> _field31;
    struct unique_ptr<CLWifiService_Type::Client, std::__1::default_delete<CLWifiService_Type::Client>> _field32;
    struct unique_ptr<CLCompassDaemonClientNotifier_Type::Client, std::__1::default_delete<CLCompassDaemonClientNotifier_Type::Client>> _field33;
    struct unique_ptr<CLBTLEFenceManager_Type::Client, std::__1::default_delete<CLBTLEFenceManager_Type::Client>> _field34;
    struct unique_ptr<CLBTLERangeManager_Type::Client, std::__1::default_delete<CLBTLERangeManager_Type::Client>> _field35;
    struct unique_ptr<CLFenceManager_Type::Client, std::__1::default_delete<CLFenceManager_Type::Client>> _field36;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field37;
    struct unique_ptr<CLGeomagneticModelProvider_Type::Client, std::__1::default_delete<CLGeomagneticModelProvider_Type::Client>> _field38;
    struct unique_ptr<CLAutopauseProvider_Type::Client, std::__1::default_delete<CLAutopauseProvider_Type::Client>> _field39;
    struct unique_ptr<CLMotionState_Type::Client, std::__1::default_delete<CLMotionState_Type::Client>> _field40;
    struct unique_ptr<CLOnBodyNotifier_Type::Client, std::__1::default_delete<CLOnBodyNotifier_Type::Client>> _field41;
    struct unique_ptr<CLStepCountNotifier_Type::Client, std::__1::default_delete<CLStepCountNotifier_Type::Client>> _field42;
    struct unique_ptr<CLOdometerNotifier_Type::Client, std::__1::default_delete<CLOdometerNotifier_Type::Client>> _field43;
    struct unique_ptr<CLMotionState_Type::Client, std::__1::default_delete<CLMotionState_Type::Client>> _field44;
    struct unique_ptr<CLNatalimetryNotifier_Type::Client, std::__1::default_delete<CLNatalimetryNotifier_Type::Client>> _field45;
    struct auto_ptr<CLSidebandOverride> _field46;
    struct unique_ptr<CLSidebandSensorFusion, std::__1::default_delete<CLSidebandSensorFusion>> _field47;
    struct unique_ptr<CLNatalimetryActivityOverride, std::__1::default_delete<CLNatalimetryActivityOverride>> _field48;
    _Bool _field49;
    double _field50;
    _Bool _field51;
    struct Dispatcher *_field52;
    id _field53;
    double _field54;
    struct {
        double _field1;
        double _field2;
        double _field3;
        double _field4;
        double _field5;
        double _field6;
        double _field7;
        double _field8;
        double _field9;
        double _field10;
        int _field11;
    } _field55;
    struct CLNameValuePair _field56;
    struct CLNameValuePair _field57;
    _Bool _field58;
    _Bool _field59;
    _Bool _field60;
    _Bool _field61;
    id _field62;
    int _field63;
    int _field64;
    _Bool _field65;
    _Bool _field66;
    _Bool _field67;
    id _field68;
    struct CLConnection *_field69;
    int _field70;
    int _field71;
    double _field72;
    long long _field73;
    double _field74;
    _Bool _field75;
    struct PauseState _field76;
    _Bool _field77;
    struct map<int, CMActivityAlarm *, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CMActivityAlarm *>>> _field78;
    _Bool _field79;
    double _field80;
    double _field81;
    double _field82;
    double _field83;
    id _field84;
    struct shared_ptr<CLPersistentTimer> _field85;
    _Bool _field86;
    _Bool _field87;
    _Bool _field88;
    _Bool _field89;
    _Bool _field90;
    struct LocationUpdateSession _field91;
    struct LocationMonitorSession _field92;
    struct MotionTrigger _field93;
    struct CLCompassSessionStatsCollector *_field94;
    struct map<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>, std::__1::less<CLBTLEBeaconRegion_Type::Region>, std::__1::allocator<std::__1::pair<const CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>>> _field95;
    double _field96;
};

struct CLDistanceCalc {
    double fM;
    double fN;
    double fRefLatRads;
    double fRefLatDegs;
    double fCosRefLat;
};

struct CLEncryptedHarvestDatabase<CLAppHarvestDatabase, std::__1::basic_string<char>, void (*)(CLAppHarvestDatabase *, const std::__1::basic_string<char>&, const CLClientLocation &, const CLAppHarvestDatabase::HarvestData &, void *), CLAppHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLCdmaCellHarvestDatabase, CLTelephonyService_Type::CdmaCell, void (*)(CLCdmaCellHarvestDatabase *, const CLTelephonyService_Type::CdmaCell &, const CLClientLocation &, const CLCdmaCellHarvestDatabase::HarvestData &, void *), CLCdmaCellHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLCellHarvestDatabase, CLTelephonyService_Type::Cell, void (*)(CLCellHarvestDatabase *, const CLTelephonyService_Type::Cell &, const CLClientLocation &, const CLCellHarvestDatabase::HarvestData &, void *), CLCellHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLLteCellHarvestDatabase, CLTelephonyService_Type::LteCell, void (*)(CLLteCellHarvestDatabase *, const CLTelephonyService_Type::LteCell &, const CLClientLocation &, const CLLteCellHarvestDatabase::HarvestData &, void *), CLLteCellHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLPassHarvestDatabase, std::__1::basic_string<char>, void (*)(CLPassHarvestDatabase *, const CLClientLocation &, const CLPassHarvestDatabase::HarvestData &, void *), CLPassHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLScdmaCellHarvestDatabase, CLTelephonyService_Type::ScdmaCell, void (*)(CLScdmaCellHarvestDatabase *, const CLTelephonyService_Type::ScdmaCell &, const CLClientLocation &, const CLScdmaCellHarvestDatabase::HarvestData &, void *), CLScdmaCellHarvestDatabase::HarvestData>;

struct CLEncryptedHarvestDatabase<CLWifiHarvestDatabase, std::__1::basic_string<char>, void (*)(CLWifiHarvestDatabase *, const std::__1::basic_string<char>&, const CLClientLocation &, const CLWifiHarvestDatabase::HarvestData &, void *), CLWifiHarvestDatabase::HarvestData>;

struct CLFileDownload;

struct CLFileDownloadHttp {
    CDUnknownFunctionPointerType *_field1;
    id _field2;
    struct __sFILE *_field3;
    unsigned long long _field4;
    CDUnknownFunctionPointerType _field5;
    void *_field6;
    _Bool _field7;
    struct CLHttpRequest _field8;
    _Bool _field9;
    int _field10;
};

struct CLFileUpdate {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    id _field3;
    CDUnknownFunctionPointerType _field4;
    void *_field5;
    struct CLFileDownload *_field6;
    struct __CFRunLoopTimer *_field7;
    int _field8;
    double _field9;
    double _field10;
    double _field11;
    double _field12;
    double _field13;
    double _field14;
    _Bool _field15;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field16;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field17;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field18;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field19;
    struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> _field20;
};

struct CLHostResolver {
    struct BasicMutex _field1;
    id _field2;
    int _field3;
    struct map<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>>> _field4;
    CDUnknownFunctionPointerType _field5;
    void *_field6;
};

struct CLHttpRequest {
    CDUnknownFunctionPointerType *_field1;
    id _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    void *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field6;
    struct __CFRunLoopTimer *_field7;
    struct __CFHTTPMessage *_field8;
    struct __CFHTTPMessage *_field9;
    struct __CFReadStream *_field10;
    double _field11;
    double _field12;
    _Bool _field13;
    struct __CFDictionary *_field14;
    struct CLPowerAssertion *_field15;
};

struct CLIndoorLogic;

struct CLLastFix {
    CDStruct_f227fc05 _field1;
    struct time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>> _field2;
    struct time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>> _field3;
};

struct CLLingerRequest {
    struct Client *_field1;
};

struct CLLocationClassificationEstimate {
    struct time_point<cl::chrono::CFAbsoluteTimeClock, std::__1::chrono::duration<long double, std::__1::ratio<1, 1>>> fTimestamp;
    int fCurrent;
    _Bool fChanged;
};

struct CLLocationEncryptedHarvestDatabase;

struct CLLocationHarvester {
    CDUnknownFunctionPointerType *_field1;
    CDUnknownFunctionPointerType *_field2;
    CDUnknownFunctionPointerType *_field3;
    CDUnknownFunctionPointerType *_field4;
    struct BasicMutex *_field5;
    id _field6;
    id _field7;
    struct unique_ptr<CLSubHarvesterIndoor, std::__1::default_delete<CLSubHarvesterIndoor>> _field8;
    struct unique_ptr<CLSubHarvesterWtw, std::__1::default_delete<CLSubHarvesterWtw>> _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    _Bool _field14;
    _Bool _field15;
    int _field16;
    int _field17;
    int _field18;
    _Bool _field19;
    _Bool _field20;
    struct Battery _field21;
    int _field22;
    _Bool _field23;
    struct HarvestRules _field24;
    struct CLDistanceCalc _field25;
    _Bool _field26;
    int _field27;
    int _field28;
    int _field29;
    int _field30;
    int _field31;
    int _field32;
    int _field33;
    int _field34;
    double _field35;
    double _field36;
    struct shared_ptr<CLCollectionRequester> _field37;
    struct CLLocationProvider *_field38;
    int _field39;
    double _field40;
    int _field41;
    struct CLServiceLocationProvider _field42;
    struct CLServiceLocationProvider _field43;
    int _field44;
    int _field45;
    CDStruct_f227fc05 _field46;
    CDStruct_f227fc05 _field47;
    CDStruct_f227fc05 _field48;
    CDStruct_f227fc05 _field49;
    CDStruct_f227fc05 _field50;
    CDStruct_f227fc05 _field51;
    struct CLMotionActivity _field52;
    _Bool _field53;
    _Bool _field54;
    _Bool _field55;
    _Bool _field56;
    struct HarvestData _field57;
    struct list<CLLocationHarvester::AppHarvestInfo, std::__1::allocator<CLLocationHarvester::AppHarvestInfo>> _field58;
    struct list<CLLocationHarvester::PassHarvestInfo, std::__1::allocator<CLLocationHarvester::PassHarvestInfo>> _field59;
    _Bool _field60;
    struct CLLocationEncryptedHarvestDatabase *_field61;
    struct CLEncryptedHarvestDatabase<CLCellHarvestDatabase, CLTelephonyService_Type::Cell, void (*)(CLCellHarvestDatabase *, const CLTelephonyService_Type::Cell &, const CLClientLocation &, const CLCellHarvestDatabase::HarvestData &, void *), CLCellHarvestDatabase::HarvestData> *_field62;
    struct CLEncryptedHarvestDatabase<CLScdmaCellHarvestDatabase, CLTelephonyService_Type::ScdmaCell, void (*)(CLScdmaCellHarvestDatabase *, const CLTelephonyService_Type::ScdmaCell &, const CLClientLocation &, const CLScdmaCellHarvestDatabase::HarvestData &, void *), CLScdmaCellHarvestDatabase::HarvestData> *_field63;
    struct CLEncryptedHarvestDatabase<CLCdmaCellHarvestDatabase, CLTelephonyService_Type::CdmaCell, void (*)(CLCdmaCellHarvestDatabase *, const CLTelephonyService_Type::CdmaCell &, const CLClientLocation &, const CLCdmaCellHarvestDatabase::HarvestData &, void *), CLCdmaCellHarvestDatabase::HarvestData> *_field64;
    struct CLEncryptedHarvestDatabase<CLLteCellHarvestDatabase, CLTelephonyService_Type::LteCell, void (*)(CLLteCellHarvestDatabase *, const CLTelephonyService_Type::LteCell &, const CLClientLocation &, const CLLteCellHarvestDatabase::HarvestData &, void *), CLLteCellHarvestDatabase::HarvestData> *_field65;
    struct CLNeighborsEncryptedHarvestDatabase<CellNeighborInfo, CLNeighborsHarvestDatabase<CellNeighborInfo>> *_field66;
    struct CLNeighborsEncryptedHarvestDatabase<ScdmaCellNeighborInfo, CLNeighborsHarvestDatabase<ScdmaCellNeighborInfo>> *_field67;
    struct CLNeighborsEncryptedHarvestDatabase<CdmaNeighborInfo, CLNeighborsHarvestDatabase<CdmaNeighborInfo>> *_field68;
    struct CLNeighborsEncryptedHarvestDatabase<LteNeighborInfo, CLNeighborsHarvestDatabase<LteNeighborInfo>> *_field69;
    struct CLEncryptedHarvestDatabase<CLWifiHarvestDatabase, std::__1::basic_string<char>, void (*)(CLWifiHarvestDatabase *, const std::__1::basic_string<char>&, const CLClientLocation &, const CLWifiHarvestDatabase::HarvestData &, void *), CLWifiHarvestDatabase::HarvestData> *_field70;
    struct CLEncryptedHarvestDatabase<CLAppHarvestDatabase, std::__1::basic_string<char>, void (*)(CLAppHarvestDatabase *, const std::__1::basic_string<char>&, const CLClientLocation &, const CLAppHarvestDatabase::HarvestData &, void *), CLAppHarvestDatabase::HarvestData> *_field71;
    struct CLEncryptedHarvestDatabase<CLPassHarvestDatabase, std::__1::basic_string<char>, void (*)(CLPassHarvestDatabase *, const CLClientLocation &, const CLPassHarvestDatabase::HarvestData &, void *), CLPassHarvestDatabase::HarvestData> *_field72;
    double _field73;
    double _field74;
    double _field75;
    double _field76;
    double _field77;
    double _field78;
    double _field79;
    double _field80;
    double _field81;
    double _field82;
    double _field83;
    double _field84;
    double _field85;
    double _field86;
    double _field87;
    double _field88;
    double _field89;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field90;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field91;
    struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> _field92;
    struct unique_ptr<CLAppMonitor_Type::Client, std::__1::default_delete<CLAppMonitor_Type::Client>> _field93;
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _field94;
    struct unique_ptr<CLGpsController_Type::Client, std::__1::default_delete<CLGpsController_Type::Client>> _field95;
    struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> _field96;
    struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> _field97;
    struct unique_ptr<CLTelephonyService_Type::Client, std::__1::default_delete<CLTelephonyService_Type::Client>> _field98;
    struct unique_ptr<CLWifiService_Type::Client, std::__1::default_delete<CLWifiService_Type::Client>> _field99;
    struct unique_ptr<CLDataProtectionManager_Type::Client, std::__1::default_delete<CLDataProtectionManager_Type::Client>> _field100;
    struct unique_ptr<CLBTA_Type::Client, std::__1::default_delete<CLBTA_Type::Client>> _field101;
    struct unique_ptr<CLOperatorSettings_Type::Client, std::__1::default_delete<CLOperatorSettings_Type::Client>> _field102;
    struct unique_ptr<CLMotionState_Type::Client, std::__1::default_delete<CLMotionState_Type::Client>> _field103;
    struct CLPersistentTimer *_field104;
    struct CLPersistentTimer *_field105;
    struct __CFRunLoopTimer *_field106;
    struct __CFRunLoopTimer *_field107;
    struct __CFRunLoopTimer *_field108;
    int _field109;
    id _field110;
    id _field111;
    id _field112;
    _Bool _field113;
    _Bool _field114;
    _Bool _field115;
    _Bool _field116;
    _Bool _field117;
    int _field118;
    int _field119;
    struct CLCircularQueue<CLLocationHarvester::RealTimeHarvestInfo> _field120;
    int _field121;
    int _field122;
    struct CLHostResolver _field123;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field124;
    unsigned int _field125;
    _Bool _field126;
    double _field127;
    struct CLPowerAssertion _field128;
    struct CLPowerAssertion _field129;
    struct CLPowerAssertion _field130;
    _Bool _field131;
    double _field132;
    _Bool _field133;
    _Bool _field134;
    _Bool _field135;
    _Bool _field136;
    _Bool _field137;
    _Bool _field138;
};

struct CLLocationProvider {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    id _field4;
    id _field5;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> _field6;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> _field7;
    int _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
};

struct CLMotionActivity {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    float _field5;
    double _field6;
    int _field7;
    double _field8;
    double _field9;
};

struct CLNameValuePair {
    CDUnknownFunctionPointerType *_field1;
    struct __CFDictionary *_field2;
};

struct CLNatalimetryActivityOverride;

struct CLNeighborsEncryptedHarvestDatabase<CdmaNeighborInfo, CLNeighborsHarvestDatabase<CdmaNeighborInfo>>;

struct CLNeighborsEncryptedHarvestDatabase<CellNeighborInfo, CLNeighborsHarvestDatabase<CellNeighborInfo>>;

struct CLNeighborsEncryptedHarvestDatabase<LteNeighborInfo, CLNeighborsHarvestDatabase<LteNeighborInfo>>;

struct CLNeighborsEncryptedHarvestDatabase<ScdmaCellNeighborInfo, CLNeighborsHarvestDatabase<ScdmaCellNeighborInfo>>;

struct CLNetworkLocationRequesterALS {
    CDUnknownFunctionPointerType *_field1;
    struct vector<CLTelephonyService_Type::Cell, std::__1::allocator<CLTelephonyService_Type::Cell>> _field2;
    struct vector<CLTelephonyService_Type::ScdmaCell, std::__1::allocator<CLTelephonyService_Type::ScdmaCell>> _field3;
    struct vector<CLTelephonyService_Type::CdmaCell, std::__1::allocator<CLTelephonyService_Type::CdmaCell>> _field4;
    struct vector<CLTelephonyService_Type::LteCell, std::__1::allocator<CLTelephonyService_Type::LteCell>> _field5;
    struct vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char>>> _field6;
    struct Listener {
        void *_field1;
        id _field2;
        CDUnknownFunctionPointerType _field3;
        CDUnknownFunctionPointerType _field4;
        CDUnknownFunctionPointerType _field5;
        CDUnknownFunctionPointerType _field6;
        CDUnknownFunctionPointerType _field7;
        CDUnknownFunctionPointerType _field8;
        CDUnknownFunctionPointerType _field9;
        CDUnknownFunctionPointerType _field10;
        CDUnknownFunctionPointerType _field11;
        CDUnknownFunctionPointerType _field12;
        CDUnknownFunctionPointerType _field13;
        CDUnknownFunctionPointerType _field14;
        CDUnknownFunctionPointerType _field15;
        CDUnknownFunctionPointerType _field16;
        CDUnknownFunctionPointerType _field17;
        CDUnknownFunctionPointerType _field18;
    } _field7;
    int _field8;
    int _field9;
    id _field10;
    id _field11;
    _Bool _field12;
    int _field13;
    struct __CFString *_field14;
    struct __CFString *_field15;
    int _field16;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field17;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field18;
};

struct CLNotifierBase {
    CDUnknownFunctionPointerType *_field1;
};

struct CLNotifierClientBase {
    CDUnknownFunctionPointerType *_field1;
};

struct CLOutdoorEstimator {
    int fLatestMatchQuality;
    struct optional<CLMotionActivity> fLatestMotionActivity;
    int fLatestProvider;
    double fLatestSpeed;
    double fLatestSpeedUncerainty;
    int fCurrentClassification;
};

struct CLPersistentStore {
    CDUnknownFunctionPointerType *_field1;
    struct __CFDictionary *_field2;
    id _field3;
    _Bool _field4;
    _Bool _field5;
    double _field6;
    struct __CFRunLoopTimer *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field10;
    int _field11;
};

struct CLPersistentTimer {
    id _field1;
    CDUnknownFunctionPointerType _field2;
    void *_field3;
    id _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field5;
};

struct CLPipelineLocationProvider {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    id _field4;
    id _field5;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> _field6;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> _field7;
    int _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    CDUnknownFunctionPointerType *_field14;
    struct unique_ptr<CLIndoorLogic, std::__1::default_delete<CLIndoorLogic>> _field15;
    id _field16;
    struct unique_ptr<CLDarwinNotifier_Type::Client, std::__1::default_delete<CLDarwinNotifier_Type::Client>> _field17;
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _field18;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field19;
    struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> _field20;
    struct unique_ptr<CLWifiService_Type::Client, std::__1::default_delete<CLWifiService_Type::Client>> _field21;
    struct unique_ptr<CLGpsController_Type::Client, std::__1::default_delete<CLGpsController_Type::Client>> _field22;
    struct unique_ptr<CLMotionState_Type::Client, std::__1::default_delete<CLMotionState_Type::Client>> _field23;
    struct CLFileDownloadHttp _field24;
    struct CLFileUpdate _field25;
    struct CLLingerRequest _field26;
    int _field27;
};

struct CLPowerAssertion {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    void *_field3;
    struct __CFString *_field4;
    double _field5;
    double _field6;
};

struct CLQmiClientAdapter;

struct CLQmiDmsManager {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct shared_ptr<CLQmiClientAdapter> _field3;
    int _field4;
    unsigned int _field5;
    _Bool _field6;
};

struct CLServiceLocationProvider {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    id _field4;
    id _field5;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> _field6;
    struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> _field7;
    int _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    struct __CLClient *_field14;
    struct __CLClient *_field15;
    struct __CLClient *_field16;
    struct __CFString *_field17;
    struct __CFString *_field18;
};

struct CLSidebandOverride;

struct CLSidebandSensorFusion;

struct CLSimulationController {
    struct BasicMutex _field1;
    id _field2;
    struct list<CLClientLocation, std::__1::allocator<CLClientLocation>> _field3;
    _Bool _field4;
    double _field5;
    CDStruct_f227fc05 _field6;
    CDStruct_f227fc05 _field7;
    CDStruct_f227fc05 _field8;
    struct __CFRunLoopTimer *_field9;
    double _field10;
    double _field11;
    double _field12;
    double _field13;
    double _field14;
    int _field15;
    int _field16;
    struct __CFURL *_field17;
};

struct CLSqliteCachedStatement {
    struct CLSqliteDatabase *fDb;
    struct sqlite3_stmt *fStatement;
};

struct CLSqliteDatabase;

struct CLStatusBarIconManager {
    struct BasicMutex _field1;
    id _field2;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field3;
    struct unique_ptr<CLGpsController_Type::Client, std::__1::default_delete<CLGpsController_Type::Client>> _field4;
    struct __CFRunLoopTimer *_field5;
    _Bool _field6;
    _Bool _field7;
    _Bool _field8[5];
    int _field9;
    struct CLNameValuePair _field10;
    double _field11[5][3];
    _Bool _field12;
};

struct CLStepCountEntry {
    double timestamp;
    double startTime;
    unsigned int count;
    double distance;
    unsigned int floorsAscended;
    unsigned int floorsDescended;
    int recordId;
};

struct CLStepCountRecorderDb {
    CDUnknownFunctionPointerType *_vptr$CLActivityRecorderDb;
    struct auto_ptr<CLSqliteDatabase> fDb;
    struct BasicMutex fMutex;
    _Bool fFatalError;
    struct deque<CLStepCountEntry, std::__1::allocator<CLStepCountEntry>> fBuffer;
    int fInternalRecordCount;
    float fSampleInterval;
    struct CLStepCountEntry fPrevEntry;
    int fMaxBufferSize;
    struct CLSqliteCachedStatement fSqlGetCount;
    struct CLSqliteCachedStatement fSqlGetAllAsc;
    struct CLSqliteCachedStatement fSqlGetSinceAsc;
    struct CLSqliteCachedStatement fSqlGetAllDesc;
    struct CLSqliteCachedStatement fSqlDeleteById;
    struct CLSqliteCachedStatement fSqlDeleteAfter;
    struct CLSqliteCachedStatement fSqlDeleteAll;
    struct CLSqliteCachedStatement fSqlInsert;
    struct CLSqliteCachedStatement fSqlShiftStartTimes;
    struct CLSqliteCachedStatement fSqlMostRecent;
    struct CLSqliteCachedStatement fSqlFirstValidEntry;
    struct CLSqliteCachedStatement fSqlLowerBound;
    struct CLSqliteCachedStatement fSqlUpperBound;
    _Bool fResetRequested;
    _Bool fResetFloorsRequested;
    CDUnknownBlockType fFinishedInsertHandler;
    CLSilo *fFinishedInsertSilo;
    unsigned int fPrevStepCount;
    unsigned int fPrevFloorsAscended;
    unsigned int fPrevFloorsDescended;
    int fOffset;
    int fFloorAscendedOffset;
    int fFloorDescendedOffset;
};

struct CLSubHarvesterIndoor;

struct CLSubHarvesterWtw;

struct CLSuggestedActionDatabase;

struct CLTileFileDownloadDetails {
    _Bool _field1;
    _Bool _field2;
    _Bool _field3;
    double _field4;
    int _field5;
    double _field6;
    _Bool _field7;
    _Bool _field8;
};

struct CLTilesManager {
    CDUnknownFunctionPointerType *_field1;
    struct BasicMutex _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    id _field4;
    id _field5;
    struct map<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>>> _field6;
    struct map<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>>> _field7;
    int _field8;
    _Bool _field9;
    struct map<TileId, CLTileFile *, std::__1::less<TileId>, std::__1::allocator<std::__1::pair<const TileId, CLTileFile *>>> _field10;
    struct DownloadState _field11;
    struct DownloadState _field12;
    double _field13;
    struct __CFRunLoopTimer *_field14;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field15;
    struct unique_ptr<CLBTA_Type::Client, std::__1::default_delete<CLBTA_Type::Client>> _field16;
    struct unique_ptr<CLDataProtectionManager_Type::Client, std::__1::default_delete<CLDataProtectionManager_Type::Client>> _field17;
    _Bool _field18;
    _Bool _field19;
    double _field20;
    double _field21;
    double _field22;
    struct TileId _field23;
    _Bool _field24;
    _Bool _field25;
    double _field26;
    double _field27;
    struct CLPersistentTimer *_field28;
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _field29;
    CDStruct_f227fc05 _field30;
    double _field31;
    double _field32;
    struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> _field33;
    int _field34;
    int _field35;
    int _field36;
    _Bool _field37;
    struct WifiServerResponseListener _field38;
    _Bool _field39;
};

struct CLTimeZoneDatabase;

struct CLTimeZoneManager {
    struct CLTimeZoneDatabase *_field1;
    struct unique_ptr<CLDarwinNotifier_Type::Client, std::__1::default_delete<CLDarwinNotifier_Type::Client>> _field2;
    struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> _field3;
    struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> _field4;
    struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> _field5;
    struct unique_ptr<CLTelephonyService_Type::Client, std::__1::default_delete<CLTelephonyService_Type::Client>> _field6;
    struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> _field7;
    id _field8;
    double _field9;
    double _field10;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field11;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field12;
    double _field13;
    CDStruct_f227fc05 _field14;
    CDStruct_f227fc05 _field15;
    CDStruct_f227fc05 _field16;
    struct CLServiceLocationProvider _field17;
    int _field18;
    int _field19;
    _Bool _field20;
    _Bool _field21;
    struct __CFRunLoopTimer *_field22;
    struct CLPersistentTimer *_field23;
    struct __CFRunLoopTimer *_field24;
    int _field25;
    double _field26;
    struct __CFRunLoopTimer *_field27;
    double _field28;
    double _field29;
    double _field30;
    int _field31;
    double _field32;
    double _field33;
    double _field34;
    double _field35;
    double _field36;
    double _field37;
    double _field38;
    double _field39;
    double _field40;
    _Bool _field41[24];
};

struct CMStrideCalRecorderDb;

struct CdmaCell;

struct Cell;

struct Client;

struct DestructionAwareMutex {
    CDUnknownFunctionPointerType *_field1;
    struct shared_ptr<DestructionAwareMutexInternal> _field2;
};

struct DestructionAwareMutexInternal;

struct Dispatcher;

struct DownloadState {
    char *_field1;
    _Bool _field2;
    double _field3;
    struct CLFileDownloadHttp *_field4;
};

struct FairPlayHWInfo_ {
    unsigned int IDLength;
    unsigned char ID[20];
};

struct HarvestData {
    double _field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field7;
    int _field8;
    int _field9;
};

struct HarvestRule {
    double _field1;
    double _field2;
    double _field3;
    int _field4;
    int _field5;
};

struct HarvestRules {
    struct HarvestRule _field1;
    struct HarvestRule _field2;
    struct HarvestRule _field3;
    struct HarvestRule _field4;
    struct HarvestRule _field5;
    struct HarvestRule _field6;
    double _field7;
};

struct LocationMonitorSession {
    struct Metric _field1;
    double _field2;
    double _field3;
    int _field4;
    int _field5;
    _Bool _field6;
};

struct LocationSystemState {
    _Bool _field1;
    _Bool _field2;
    _Bool _field3;
    _Bool _field4;
    _Bool _field5;
    int _field6;
    _Bool _field7;
    int _field8;
    int _field9;
};

struct LocationUpdateSession {
    struct Metric _field1;
    struct LocationSystemState _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    _Bool _field9;
    int _field10;
};

struct LteCell;

struct Metric {
    _Bool _field1;
    double _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
};

struct MonitoredRegion {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned short _field3;
    unsigned short _field4;
    int _field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field7;
    int _field8;
};

struct MotionTrigger {
    struct Metric _field1;
    double _field2;
    int _field3;
    int _field4;
    struct map<std::__1::basic_string<char>, int, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, int>>> _field5;
};

struct MutexInfo;

struct Name {
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field4;
    _Bool _field5;
};

struct PauseState {
    _Bool _field1;
    _Bool _field2;
    _Bool _field3;
};

struct RealTimeHarvestInfo;

struct RegInfo {
    double _field1;
    double _field2;
    CDStruct_f227fc05 _field3;
    double _field4;
    _Bool _field5;
    _Bool _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field7;
    double _field8;
    int _field9;
    int _field10;
};

struct SBSProcessAssertion;

struct ScdmaCell;

struct TechnologyStatus {
    int _field1;
    _Bool _field2;
};

struct TileId {
    int _field1;
    int _field2;
    int _field3;
    unsigned long long _field4;
};

struct WifiServerResponseListener {
    CDUnknownFunctionPointerType *_field1;
    struct map<TileId, CLTilesManager::WifiServerResponseListenerData, std::__1::less<TileId>, std::__1::allocator<std::__1::pair<const TileId, CLTilesManager::WifiServerResponseListenerData>>> _field2;
};

struct _GEOTileKey {
    unsigned int :6;
    unsigned int :26;
    unsigned int :26;
    unsigned int :6;
    unsigned int :8;
    unsigned int :8;
    unsigned int :8;
    unsigned int :1;
    unsigned int :7;
    unsigned char _field1[4];
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct __CFDictionary;

struct __CFHTTPMessage;

struct __CFRunLoopTimer;

struct __CFString;

struct __CLClient;

struct __list_node<CLApplicationLifecycleManager::PendingLaunch, void *>;

struct __list_node<CLClientLocation, void *>;

struct __list_node<CLLocationHarvester::AppHarvestInfo, void *>;

struct __list_node<CLLocationHarvester::PassHarvestInfo, void *>;

struct __list_node<std::__1::shared_ptr<CLConnectionMessage>, void *>;

struct __shared_weak_count;

struct __tree_end_node<std::__1::__tree_node_base<void *>*> {
    struct __tree_node_base<void *> *__left_;
};

struct a4;

struct a8;

struct aligned_storage<CLClientLocation> {
    union dummy_u {
        char data[128];
        struct a4 aligner_;
    } dummy_;
};

struct aligned_storage<CLLastFix> {
    union dummy_u {
        char data[144];
        struct a8 aligner_;
    } dummy_;
};

struct aligned_storage<CLMotionActivity> {
    union dummy_u {
        char data[56];
        struct a8 aligner_;
    } dummy_;
};

struct aligned_storage<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>>> {
    union dummy_u {
        char data[8];
        struct a8 aligner_;
    } dummy_;
};

struct aligned_storage<std::__1::vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>>> {
    union dummy_u {
        char data[24];
        struct a8 aligner_;
    } dummy_;
};

struct auto_ptr<CLSidebandOverride> {
    struct CLSidebandOverride *_field1;
};

struct auto_ptr<CLSqliteDatabase> {
    struct CLSqliteDatabase *__ptr_;
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *__data_;
                    unsigned long long __size_;
                    unsigned long long __cap_;
                } __l;
                struct __short {
                    char __data_[23];
                    struct {
                        unsigned char __size_;
                    } ;
                } __s;
                struct __raw {
                    unsigned long long __words[3];
                } __r;
            } ;
        } __first_;
    } __r_;
};

struct deque<CLStepCountEntry, std::__1::allocator<CLStepCountEntry>> {
    struct __split_buffer<CLStepCountEntry *, std::__1::allocator<CLStepCountEntry *>> {
        struct CLStepCountEntry **__first_;
        struct CLStepCountEntry **__begin_;
        struct CLStepCountEntry **__end_;
        struct __compressed_pair<CLStepCountEntry **, std::__1::allocator<CLStepCountEntry *>> {
            struct CLStepCountEntry **__first_;
        } __end_cap_;
    } __map_;
    unsigned long long __start_;
    struct __compressed_pair<unsigned long, std::__1::allocator<CLStepCountEntry>> {
        unsigned long long __first_;
    } __size_;
};

struct deque<std::__1::pair<double, unsigned int>, std::__1::allocator<std::__1::pair<double, unsigned int>>> {
    struct __split_buffer<std::__1::pair<double, unsigned int>*, std::__1::allocator<std::__1::pair<double, unsigned int>*>> {
        struct pair<double, unsigned int> **__first_;
        struct pair<double, unsigned int> **__begin_;
        struct pair<double, unsigned int> **__end_;
        struct __compressed_pair<std::__1::pair<double, unsigned int>**, std::__1::allocator<std::__1::pair<double, unsigned int>*>> {
            struct pair<double, unsigned int> **__first_;
        } __end_cap_;
    } __map_;
    unsigned long long __start_;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::pair<double, unsigned int>>> {
        unsigned long long __first_;
    } __size_;
};

struct duration<long double, std::__1::ratio<1, 1>> {
    long double __rep_;
};

struct duration<long long, std::__1::ratio<1, 1000000000>> {
    long long __rep_;
};

struct list<CLApplicationLifecycleManager::PendingLaunch, std::__1::allocator<CLApplicationLifecycleManager::PendingLaunch>> {
    struct __list_node_base<CLApplicationLifecycleManager::PendingLaunch, void *> {
        struct __list_node<CLApplicationLifecycleManager::PendingLaunch, void *> *_field1;
        struct __list_node<CLApplicationLifecycleManager::PendingLaunch, void *> *_field2;
    } _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<CLApplicationLifecycleManager::PendingLaunch, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<CLClientLocation, std::__1::allocator<CLClientLocation>> {
    struct __list_node_base<CLClientLocation, void *> {
        struct __list_node<CLClientLocation, void *> *_field1;
        struct __list_node<CLClientLocation, void *> *_field2;
    } _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<CLClientLocation, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<CLLocationHarvester::AppHarvestInfo, std::__1::allocator<CLLocationHarvester::AppHarvestInfo>> {
    struct __list_node_base<CLLocationHarvester::AppHarvestInfo, void *> {
        struct __list_node<CLLocationHarvester::AppHarvestInfo, void *> *_field1;
        struct __list_node<CLLocationHarvester::AppHarvestInfo, void *> *_field2;
    } _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<CLLocationHarvester::AppHarvestInfo, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<CLLocationHarvester::PassHarvestInfo, std::__1::allocator<CLLocationHarvester::PassHarvestInfo>> {
    struct __list_node_base<CLLocationHarvester::PassHarvestInfo, void *> {
        struct __list_node<CLLocationHarvester::PassHarvestInfo, void *> *_field1;
        struct __list_node<CLLocationHarvester::PassHarvestInfo, void *> *_field2;
    } _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<CLLocationHarvester::PassHarvestInfo, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct list<std::__1::shared_ptr<CLConnectionMessage>, std::__1::allocator<std::__1::shared_ptr<CLConnectionMessage>>> {
    struct __list_node_base<std::__1::shared_ptr<CLConnectionMessage>, void *> {
        struct __list_node<std::__1::shared_ptr<CLConnectionMessage>, void *> *_field1;
        struct __list_node<std::__1::shared_ptr<CLConnectionMessage>, void *> *_field2;
    } _field1;
    struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__list_node<std::__1::shared_ptr<CLConnectionMessage>, void *>>> {
        unsigned long long _field1;
    } _field2;
};

struct map<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>, std::__1::less<CLBTLEBeaconRegion_Type::Region>, std::__1::allocator<std::__1::pair<const CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>>> {
    struct __tree<std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>, std::__1::__map_value_compare<CLBTLEBeaconRegion_Type::Region, std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>, std::__1::less<CLBTLEBeaconRegion_Type::Region>, true>, std::__1::allocator<std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>>> {
        struct __tree_node<std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<CLBTLEBeaconRegion_Type::Region, std::__1::__value_type<CLBTLEBeaconRegion_Type::Region, std::__1::set<CLBTLEBeaconRegion_Type::MonitoredRegion, std::__1::less<CLBTLEBeaconRegion_Type::MonitoredRegion>, std::__1::allocator<CLBTLEBeaconRegion_Type::MonitoredRegion>>>, std::__1::less<CLBTLEBeaconRegion_Type::Region>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<SEL *, CLIntersiloInterfaceSelectorInfo *, std::__1::less<SEL *>, std::__1::allocator<std::__1::pair<SEL *const, CLIntersiloInterfaceSelectorInfo *>>> {
    struct __tree<std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>, std::__1::__map_value_compare<SEL *, std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>, std::__1::less<SEL *>, true>, std::__1::allocator<std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>>> {
        struct __tree_node<std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>, void *> *__begin_node_;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> __first_;
        } __pair1_;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<SEL *, std::__1::__value_type<SEL *, CLIntersiloInterfaceSelectorInfo *>, std::__1::less<SEL *>, true>> {
            unsigned long long __first_;
        } __pair3_;
    } __tree_;
};

struct map<TileId, CLTileFile *, std::__1::less<TileId>, std::__1::allocator<std::__1::pair<const TileId, CLTileFile *>>> {
    struct __tree<std::__1::__value_type<TileId, CLTileFile *>, std::__1::__map_value_compare<TileId, std::__1::__value_type<TileId, CLTileFile *>, std::__1::less<TileId>, true>, std::__1::allocator<std::__1::__value_type<TileId, CLTileFile *>>> {
        struct __tree_node<std::__1::__value_type<TileId, CLTileFile *>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<TileId, CLTileFile *>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<TileId, std::__1::__value_type<TileId, CLTileFile *>, std::__1::less<TileId>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<TileId, CLTilesManager::WifiServerResponseListenerData, std::__1::less<TileId>, std::__1::allocator<std::__1::pair<const TileId, CLTilesManager::WifiServerResponseListenerData>>> {
    struct __tree<std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>, std::__1::__map_value_compare<TileId, std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>, std::__1::less<TileId>, true>, std::__1::allocator<std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>>> {
        struct __tree_node<std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<TileId, std::__1::__value_type<TileId, CLTilesManager::WifiServerResponseListenerData>, std::__1::less<TileId>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<id<CLSignificantVisitManagerClientProtocol>, NSString *, std::__1::less<id<CLSignificantVisitManagerClientProtocol>>, std::__1::allocator<std::__1::pair<const id<CLSignificantVisitManagerClientProtocol>, NSString *>>> {
    struct __tree<std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>, std::__1::__map_value_compare<id<CLSignificantVisitManagerClientProtocol>, std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>, std::__1::less<id<CLSignificantVisitManagerClientProtocol>>, true>, std::__1::allocator<std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>>> {
        struct __tree_node<std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>, void *> *__begin_node_;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> __first_;
        } __pair1_;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<id<CLSignificantVisitManagerClientProtocol>, std::__1::__value_type<id<CLSignificantVisitManagerClientProtocol>, NSString *>, std::__1::less<id<CLSignificantVisitManagerClientProtocol>>, true>> {
            unsigned long long __first_;
        } __pair3_;
    } __tree_;
};

struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> {
    struct __tree<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>>> {
        struct __tree_node<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::ClientNotifications>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> {
    struct __tree<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>>> {
        struct __tree_node<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLLocationProvider_Type::Notification, CLLocationProvider_Type::NotificationData, char, CLLocationProvider_Type::RegInfo>::Notification>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>>> {
    struct __tree<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>>> {
        struct __tree_node<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::ClientNotifications>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>>> {
    struct __tree<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>>> {
        struct __tree_node<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, CLNotifier<CLTilesManager_Type::Notification, CLTilesManager_Type::NotificationData, char, char>::Notification>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<int, CMActivityAlarm *, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, CMActivityAlarm *>>> {
    struct __tree<std::__1::__value_type<int, CMActivityAlarm *>, std::__1::__map_value_compare<int, std::__1::__value_type<int, CMActivityAlarm *>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, CMActivityAlarm *>>> {
        struct __tree_node<std::__1::__value_type<int, CMActivityAlarm *>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<int, CMActivityAlarm *>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<int, std::__1::__value_type<int, CMActivityAlarm *>, std::__1::less<int>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<std::__1::basic_string<char>, bool, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, bool>>> {
    struct __tree<std::__1::__value_type<std::__1::basic_string<char>, bool>, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, bool>, std::__1::less<std::__1::basic_string<char>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char>, bool>>> {
        struct __tree_node<std::__1::__value_type<std::__1::basic_string<char>, bool>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, bool>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, bool>, std::__1::less<std::__1::basic_string<char>>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<std::__1::basic_string<char>, int, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, int>>> {
    struct __tree<std::__1::__value_type<std::__1::basic_string<char>, int>, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, int>, std::__1::less<std::__1::basic_string<char>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char>, int>>> {
        struct __tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, int>, std::__1::less<std::__1::basic_string<char>>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>>> {
    struct __tree<std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>, std::__1::less<std::__1::basic_string<char>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>>> {
        struct __tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<std::__1::basic_string<char>, std::__1::__value_type<std::__1::basic_string<char>, std::__1::shared_ptr<CLHostEntry>>, std::__1::less<std::__1::basic_string<char>>, true>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct map<unsigned long, int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, int>>> {
    struct __tree<std::__1::__value_type<unsigned long, int>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, int>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, int>>> {
        struct __tree_node<std::__1::__value_type<unsigned long, int>, void *> *__begin_node_;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, int>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> __first_;
        } __pair1_;
        struct __compressed_pair<unsigned long, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, int>, std::__1::less<unsigned long>, true>> {
            unsigned long long __first_;
        } __pair3_;
    } __tree_;
};

struct optional<CLClientLocation> {
    _Bool m_initialized;
    struct aligned_storage<CLClientLocation> m_storage;
};

struct optional<CLLastFix> {
    _Bool m_initialized;
    struct aligned_storage<CLLastFix> m_storage;
};

struct optional<CLMotionActivity> {
    _Bool m_initialized;
    struct aligned_storage<CLMotionActivity> m_storage;
};

struct optional<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>>> {
    _Bool m_initialized;
    struct aligned_storage<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>>> m_storage;
};

struct optional<std::__1::vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>>> {
    _Bool m_initialized;
    struct aligned_storage<std::__1::vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>>> m_storage;
};

struct pair<double, CLMotionActivity::Type>;

struct pair<double, unsigned int>;

struct queue<std::__1::pair<double, unsigned int>, std::__1::deque<std::__1::pair<double, unsigned int>, std::__1::allocator<std::__1::pair<double, unsigned int>>>> {
    struct deque<std::__1::pair<double, unsigned int>, std::__1::allocator<std::__1::pair<double, unsigned int>>> c;
};

struct set<CMActivityAlarm *, CLActivityAlarmConcentrator::AlarmCompare, std::__1::allocator<CMActivityAlarm *>> {
    struct __tree<CMActivityAlarm *, CLActivityAlarmConcentrator::AlarmCompare, std::__1::allocator<CMActivityAlarm *>> {
        struct __tree_node<CMActivityAlarm *, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<CMActivityAlarm *, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, CLActivityAlarmConcentrator::AlarmCompare> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>> {
    struct __tree<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>> {
        struct __tree_node<std::__1::basic_string<char>, void *> *_field1;
        struct __compressed_pair<std::__1::__tree_end_node<std::__1::__tree_node_base<void *>*>, std::__1::allocator<std::__1::__tree_node<std::__1::basic_string<char>, void *>>> {
            struct __tree_end_node<std::__1::__tree_node_base<void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::less<std::__1::basic_string<char>>> {
            unsigned long long _field1;
        } _field3;
    } _field1;
};

struct shared_ptr<CLBatchedLocations> {
    struct CLBatchedLocations *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<CLCollectionRequester> {
    struct CLCollectionRequester *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<CLPersistentTimer> {
    struct CLPersistentTimer *__ptr_;
    struct __shared_weak_count *__cntrl_;
};

struct shared_ptr<CLQmiClientAdapter> {
    struct CLQmiClientAdapter *_field1;
    struct __shared_weak_count *_field2;
};

struct shared_ptr<CMStrideCalRecorderDb> {
    struct CMStrideCalRecorderDb *__ptr_;
    struct __shared_weak_count *__cntrl_;
};

struct shared_ptr<DestructionAwareMutexInternal> {
    struct DestructionAwareMutexInternal *_field1;
    struct __shared_weak_count *_field2;
};

struct sqlite3_stmt;

struct time_point<cl::chrono::CFAbsoluteTimeClock, std::__1::chrono::duration<long double, std::__1::ratio<1, 1>>> {
    duration_b9a348d0 __d_;
};

struct time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>> {
    duration_673274cf _field1;
};

struct unique_ptr<CLAppMonitor_Type::Client, std::__1::default_delete<CLAppMonitor_Type::Client>> {
    struct __compressed_pair<CLAppMonitor_Type::Client *, std::__1::default_delete<CLAppMonitor_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLAutopauseProvider_Type::Client, std::__1::default_delete<CLAutopauseProvider_Type::Client>> {
    struct __compressed_pair<CLAutopauseProvider_Type::Client *, std::__1::default_delete<CLAutopauseProvider_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLBTA_Type::Client, std::__1::default_delete<CLBTA_Type::Client>> {
    struct __compressed_pair<CLBTA_Type::Client *, std::__1::default_delete<CLBTA_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLBTLEFenceManager_Type::Client, std::__1::default_delete<CLBTLEFenceManager_Type::Client>> {
    struct __compressed_pair<CLBTLEFenceManager_Type::Client *, std::__1::default_delete<CLBTLEFenceManager_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLBTLERangeManager_Type::Client, std::__1::default_delete<CLBTLERangeManager_Type::Client>> {
    struct __compressed_pair<CLBTLERangeManager_Type::Client *, std::__1::default_delete<CLBTLERangeManager_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLBundleLocationProvider_Type::Client, std::__1::default_delete<CLBundleLocationProvider_Type::Client>> {
    struct __compressed_pair<CLBundleLocationProvider_Type::Client *, std::__1::default_delete<CLBundleLocationProvider_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLClientManager_Type::Client, std::__1::default_delete<CLClientManager_Type::Client>> {
    struct __compressed_pair<CLClientManager_Type::Client *, std::__1::default_delete<CLClientManager_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLCompassDaemonClientNotifier_Type::Client, std::__1::default_delete<CLCompassDaemonClientNotifier_Type::Client>> {
    struct __compressed_pair<CLCompassDaemonClientNotifier_Type::Client *, std::__1::default_delete<CLCompassDaemonClientNotifier_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLDaemonStatus_Type::Client, std::__1::default_delete<CLDaemonStatus_Type::Client>> {
    struct __compressed_pair<CLDaemonStatus_Type::Client *, std::__1::default_delete<CLDaemonStatus_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLDarwinNotifier_Type::Client, std::__1::default_delete<CLDarwinNotifier_Type::Client>> {
    struct __compressed_pair<CLDarwinNotifier_Type::Client *, std::__1::default_delete<CLDarwinNotifier_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLDataProtectionManager_Type::Client, std::__1::default_delete<CLDataProtectionManager_Type::Client>> {
    struct __compressed_pair<CLDataProtectionManager_Type::Client *, std::__1::default_delete<CLDataProtectionManager_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLFenceManager_Type::Client, std::__1::default_delete<CLFenceManager_Type::Client>> {
    struct __compressed_pair<CLFenceManager_Type::Client *, std::__1::default_delete<CLFenceManager_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLFilteredLocationController_Type::Client, std::__1::default_delete<CLFilteredLocationController_Type::Client>> {
    struct __compressed_pair<CLFilteredLocationController_Type::Client *, std::__1::default_delete<CLFilteredLocationController_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLGeomagneticModelProvider_Type::Client, std::__1::default_delete<CLGeomagneticModelProvider_Type::Client>> {
    struct __compressed_pair<CLGeomagneticModelProvider_Type::Client *, std::__1::default_delete<CLGeomagneticModelProvider_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLGpsController_Type::Client, std::__1::default_delete<CLGpsController_Type::Client>> {
    struct __compressed_pair<CLGpsController_Type::Client *, std::__1::default_delete<CLGpsController_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLIndoorLogic, std::__1::default_delete<CLIndoorLogic>> {
    struct __compressed_pair<CLIndoorLogic *, std::__1::default_delete<CLIndoorLogic>> {
        struct CLIndoorLogic *_field1;
    } _field1;
};

struct unique_ptr<CLLocationController_Type::Client, std::__1::default_delete<CLLocationController_Type::Client>> {
    struct __compressed_pair<CLLocationController_Type::Client *, std::__1::default_delete<CLLocationController_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLLocationProvider_Type::Client, std::__1::default_delete<CLLocationProvider_Type::Client>> {
    struct __compressed_pair<CLLocationProvider_Type::Client *, std::__1::default_delete<CLLocationProvider_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLMotionState_Type::Client, std::__1::default_delete<CLMotionState_Type::Client>> {
    struct __compressed_pair<CLMotionState_Type::Client *, std::__1::default_delete<CLMotionState_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLNatalimetryActivityOverride, std::__1::default_delete<CLNatalimetryActivityOverride>> {
    struct __compressed_pair<CLNatalimetryActivityOverride *, std::__1::default_delete<CLNatalimetryActivityOverride>> {
        struct CLNatalimetryActivityOverride *_field1;
    } _field1;
};

struct unique_ptr<CLNatalimetryNotifier_Type::Client, std::__1::default_delete<CLNatalimetryNotifier_Type::Client>> {
    struct __compressed_pair<CLNatalimetryNotifier_Type::Client *, std::__1::default_delete<CLNatalimetryNotifier_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLOdometerNotifier_Type::Client, std::__1::default_delete<CLOdometerNotifier_Type::Client>> {
    struct __compressed_pair<CLOdometerNotifier_Type::Client *, std::__1::default_delete<CLOdometerNotifier_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLOnBodyNotifier_Type::Client, std::__1::default_delete<CLOnBodyNotifier_Type::Client>> {
    struct __compressed_pair<CLOnBodyNotifier_Type::Client *, std::__1::default_delete<CLOnBodyNotifier_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLOperatorSettings_Type::Client, std::__1::default_delete<CLOperatorSettings_Type::Client>> {
    struct __compressed_pair<CLOperatorSettings_Type::Client *, std::__1::default_delete<CLOperatorSettings_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLServiceLocationProvider_Type::Client, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> {
    struct __compressed_pair<CLServiceLocationProvider_Type::Client *, std::__1::default_delete<CLServiceLocationProvider_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLSidebandSensorFusion, std::__1::default_delete<CLSidebandSensorFusion>> {
    struct __compressed_pair<CLSidebandSensorFusion *, std::__1::default_delete<CLSidebandSensorFusion>> {
        struct CLSidebandSensorFusion *_field1;
    } _field1;
};

struct unique_ptr<CLSignificantChangeManager_Type::Client, std::__1::default_delete<CLSignificantChangeManager_Type::Client>> {
    struct __compressed_pair<CLSignificantChangeManager_Type::Client *, std::__1::default_delete<CLSignificantChangeManager_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLStepCountNotifier_Type::Client, std::__1::default_delete<CLStepCountNotifier_Type::Client>> {
    struct __compressed_pair<CLStepCountNotifier_Type::Client *, std::__1::default_delete<CLStepCountNotifier_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct unique_ptr<CLSubHarvesterIndoor, std::__1::default_delete<CLSubHarvesterIndoor>> {
    struct __compressed_pair<CLSubHarvesterIndoor *, std::__1::default_delete<CLSubHarvesterIndoor>> {
        struct CLSubHarvesterIndoor *_field1;
    } _field1;
};

struct unique_ptr<CLSubHarvesterWtw, std::__1::default_delete<CLSubHarvesterWtw>> {
    struct __compressed_pair<CLSubHarvesterWtw *, std::__1::default_delete<CLSubHarvesterWtw>> {
        struct CLSubHarvesterWtw *_field1;
    } _field1;
};

struct unique_ptr<CLSuggestedActionDatabase, std::__1::default_delete<CLSuggestedActionDatabase>> {
    struct __compressed_pair<CLSuggestedActionDatabase *, std::__1::default_delete<CLSuggestedActionDatabase>> {
        struct CLSuggestedActionDatabase *__first_;
    } __ptr_;
};

struct unique_ptr<CLTelephonyService_Type::Client, std::__1::default_delete<CLTelephonyService_Type::Client>> {
    struct __compressed_pair<CLTelephonyService_Type::Client *, std::__1::default_delete<CLTelephonyService_Type::Client>> {
        struct Client *_field1;
    } _field1;
};

struct unique_ptr<CLWifiService_Type::Client, std::__1::default_delete<CLWifiService_Type::Client>> {
    struct __compressed_pair<CLWifiService_Type::Client *, std::__1::default_delete<CLWifiService_Type::Client>> {
        struct Client *__first_;
    } __ptr_;
};

struct vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>> {
    struct AvailabilityTile *_field1;
    struct AvailabilityTile *_field2;
    struct __compressed_pair<AvailabilityTile *, std::__1::allocator<AvailabilityTile>> {
        struct AvailabilityTile *_field1;
    } _field3;
};

struct vector<CLClientOdometerBuffered, std::__1::allocator<CLClientOdometerBuffered>> {
    CDStruct_183601bc *_field1;
    CDStruct_183601bc *_field2;
    struct __compressed_pair<CLClientOdometerBuffered *, std::__1::allocator<CLClientOdometerBuffered>> {
        CDStruct_183601bc *_field1;
    } _field3;
};

struct vector<CLLocationHarvester::RealTimeHarvestInfo, std::__1::allocator<CLLocationHarvester::RealTimeHarvestInfo>> {
    struct RealTimeHarvestInfo *_field1;
    struct RealTimeHarvestInfo *_field2;
    struct __compressed_pair<CLLocationHarvester::RealTimeHarvestInfo *, std::__1::allocator<CLLocationHarvester::RealTimeHarvestInfo>> {
        struct RealTimeHarvestInfo *_field1;
    } _field3;
};

struct vector<CLTelephonyService_Type::CdmaCell, std::__1::allocator<CLTelephonyService_Type::CdmaCell>> {
    struct CdmaCell *_field1;
    struct CdmaCell *_field2;
    struct __compressed_pair<CLTelephonyService_Type::CdmaCell *, std::__1::allocator<CLTelephonyService_Type::CdmaCell>> {
        struct CdmaCell *_field1;
    } _field3;
};

struct vector<CLTelephonyService_Type::Cell, std::__1::allocator<CLTelephonyService_Type::Cell>> {
    struct Cell *_field1;
    struct Cell *_field2;
    struct __compressed_pair<CLTelephonyService_Type::Cell *, std::__1::allocator<CLTelephonyService_Type::Cell>> {
        struct Cell *_field1;
    } _field3;
};

struct vector<CLTelephonyService_Type::LteCell, std::__1::allocator<CLTelephonyService_Type::LteCell>> {
    struct LteCell *_field1;
    struct LteCell *_field2;
    struct __compressed_pair<CLTelephonyService_Type::LteCell *, std::__1::allocator<CLTelephonyService_Type::LteCell>> {
        struct LteCell *_field1;
    } _field3;
};

struct vector<CLTelephonyService_Type::ScdmaCell, std::__1::allocator<CLTelephonyService_Type::ScdmaCell>> {
    struct ScdmaCell *_field1;
    struct ScdmaCell *_field2;
    struct __compressed_pair<CLTelephonyService_Type::ScdmaCell *, std::__1::allocator<CLTelephonyService_Type::ScdmaCell>> {
        struct ScdmaCell *_field1;
    } _field3;
};

struct vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char>>> {
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct __compressed_pair<std::__1::basic_string<char>*, std::__1::allocator<std::__1::basic_string<char>>> {
        struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field1;
    } _field3;
};

struct vector<std::__1::pair<double, CLMotionActivity::Type>, std::__1::allocator<std::__1::pair<double, CLMotionActivity::Type>>> {
    struct pair<double, CLMotionActivity::Type> *__begin_;
    struct pair<double, CLMotionActivity::Type> *__end_;
    struct __compressed_pair<std::__1::pair<double, CLMotionActivity::Type>*, std::__1::allocator<std::__1::pair<double, CLMotionActivity::Type>>> {
        struct pair<double, CLMotionActivity::Type> *__first_;
    } __end_cap_;
};

struct weak_ptr<CLCollectionRequester> {
    struct CLCollectionRequester *_field1;
    struct __shared_weak_count *_field2;
};

#if 0
// Names with conflicting types:
typedef struct {
    CDStruct_f227fc05 _field1;
    struct {
        double _field1;
        double _field2;
        double _field3;
        double _field4;
        float _field5;
        float _field6;
        float _field7;
        _Bool _field8;
        int _field9;
        CDStruct_c3b9c2ee _field10;
        double _field11;
        int _field12;
        int _field13;
        _Bool _field14;
    } _field2;
    struct shared_ptr<CLBatchedLocations> _field3;
    struct TechnologyStatus _field4;
    _Bool _field5;
    double _field6;
    int _field7;
    CDStruct_c3b9c2ee _field8;
    CDStruct_c3b9c2ee _field9;
    struct vector<CLClientOdometerBuffered, std::__1::allocator<CLClientOdometerBuffered>> _field10;
} NotificationData_3cb2d7d5;

typedef struct {
    struct Name _field1;
    _Bool _field2;
    int _field3;
    int _field4;
} NotificationData_a938e171;

#endif

#pragma mark Typedef'd Structures

typedef struct {
    double *list;
    unsigned long long count;
    unsigned long long size;
} CDStruct_82f37d05;

typedef struct {
    int *list;
    unsigned long long count;
    unsigned long long size;
} CDStruct_95bda58d;

typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    float _field1;
    float _field2;
} CDStruct_b2fbf00d;

typedef struct CDStruct_183601bc;

typedef struct {
    int _field1;
    CDStruct_c3b9c2ee _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
    double _field10;
    int _field11;
    double _field12;
    int _field13;
    CDStruct_c3b9c2ee _field14;
    double _field15;
    int _field16;
} CDStruct_f227fc05;

typedef struct {
    CDStruct_c3b9c2ee _field1;
    double _field2;
} CDStruct_88bbbd05;

typedef struct {
    struct {
        id _field1;
        char *_field2;
        unsigned long long _field3;
        unsigned long long _field4;
        unsigned long long _field5;
        unsigned long long _field6;
        unsigned int _field7;
        unsigned long long _field8;
        _Bool _field9;
        unsigned long long _field10;
        float _field11;
        unsigned long long _field12;
        id _field13;
        int _field14;
    } _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    int _field4;
    int _field5;
    int _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    union {
        struct {
            CDStruct_b2fbf00d _field1;
            CDStruct_b2fbf00d _field2;
        } _field1;
        struct {
            float _field1;
            float _field2;
            float _field3;
            float _field4;
        } _field2;
    } _field9;
    CDStruct_183601bc *_field10;
    struct {
        unsigned short _field1[2];
        unsigned short _field2[2];
    } _field11;
    unsigned char _field12;
} CDStruct_6cf27ba1;

// Ambiguous groups
typedef struct {
    unsigned int arfcn:1;
    unsigned int ecn0:1;
    unsigned int psc:1;
    unsigned int rat:1;
    unsigned int rscp:1;
    unsigned int serverHash:1;
    unsigned int transmit:1;
} CDStruct_3769fefd;

typedef struct {
    unsigned int arfcn:1;
    unsigned int psc:1;
} CDStruct_6bbaae90;

typedef struct duration<long double, std::__1::ratio<1, 1>> {
    long double __rep_;
} duration_b9a348d0;

typedef struct duration<long long, std::__1::ratio<1, 1000000000>> {
    long long __rep_;
} duration_673274cf;

typedef struct optional<CLClientLocation> {
    _Bool m_initialized;
    struct aligned_storage<CLClientLocation> m_storage;
} optional_b4afca65;

typedef struct optional<CLLastFix> {
    _Bool m_initialized;
    struct aligned_storage<CLLastFix> m_storage;
} optional_72c1223f;

typedef struct optional<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>>> {
    _Bool m_initialized;
    struct aligned_storage<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>>> m_storage;
} optional_830905b6;

typedef struct vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>> {
    struct AvailabilityTile *_field1;
    struct AvailabilityTile *_field2;
    struct __compressed_pair<AvailabilityTile *, std::__1::allocator<AvailabilityTile>> {
        struct AvailabilityTile *_field1;
    } _field3;
} vector_bb831d88;

