//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "EAAccessoryDelegate.h"

@class EAAccessory, NSString;

@interface CLAccessoryObserver : NSObject <EAAccessoryDelegate>
{
    EAAccessory *fAccessory;
    struct CLAccessoryObserverListener fListener;
    _Bool _iAPTimeSyncEnable;
}

@property(nonatomic) _Bool iAPTimeSyncEnable; // @synthesize iAPTimeSyncEnable=_iAPTimeSyncEnable;
- (id).cxx_construct;
- (void)onStarkTimeSyncNotification:(id)arg1;
- (void)ephemerisURLRequested:(id)arg1;
- (void)locationPointDataRequested:(id)arg1;
- (void)timeRequested:(id)arg1;
- (void)nmeaReceived:(id)arg1;
- (void)accessoryDisconnected:(id)arg1;
- (void)accessoryConnected:(id)arg1;
- (_Bool)setupEphemeris;
- (_Bool)setupAccessory:(id)arg1;
- (_Bool)sendEphemeris:(id)arg1;
- (_Bool)sendReferenceTime:(double)arg1 locationLatitude:(double)arg2 longitude:(double)arg3 accuracy:(double)arg4;
- (_Bool)sendReferenceTime:(double)arg1;
- (void)accessoryDidDisconnect:(id)arg1;
- (_Bool)stopLocation;
- (_Bool)startLocation;
- (void)dealloc;
- (id)initWithListener:(const struct CLAccessoryObserverListener *)arg1 timeSync:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

