//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_xpc_object>;

@interface CLBackgroundTaskAgent : NSObject
{
    NSMutableDictionary *_handlers;
    NSObject<OS_xpc_object> *_queuedJobs;
}

+ (id)sharedAgent;
+ (void)initialize;
- (void)removeJobs;
- (void)removeJobForName:(id)arg1;
- (id)copyJobForName:(id)arg1;
- (void)setJob:(id)arg1 forName:(id)arg2;
- (void)attachName:(id)arg1 toHandler:(CDUnknownBlockType)arg2 dispatchQueue:(id)arg3;
- (void)dealloc;
- (id)init;

@end

