//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface CLIndoorState : NSObject
{
    struct CLOutdoorEstimator _outdoorEstimator;
    optional_72c1223f _latestPosition;
    optional_830905b6 _lastIndoorError;
    struct optional<std::__1::vector<AvailabilityTile, std::__1::allocator<AvailabilityTile>>> _availabilityTiles;
    _Bool _wifiPowered;
    _Bool _gpsAssistanceRequested;
    _Bool _keybagLocked;
    _Bool _fSpectatingLocation;
    int _pipelinedSeeded;
    int _state;
    int _latestReason;
    NSSet *_pipelinedVenues;
    double _availabilityZScoreConfidenceInterval;
    struct CLLocationClassificationEstimate _latestOutdoorEstimate;
}

@property(nonatomic) int latestReason; // @synthesize latestReason=_latestReason;
@property(nonatomic) struct CLLocationClassificationEstimate latestOutdoorEstimate; // @synthesize latestOutdoorEstimate=_latestOutdoorEstimate;
@property(nonatomic) double availabilityZScoreConfidenceInterval; // @synthesize availabilityZScoreConfidenceInterval=_availabilityZScoreConfidenceInterval;
@property(nonatomic) _Bool fSpectatingLocation; // @synthesize fSpectatingLocation=_fSpectatingLocation;
@property(nonatomic) _Bool keybagLocked; // @synthesize keybagLocked=_keybagLocked;
@property(nonatomic) _Bool gpsAssistanceRequested; // @synthesize gpsAssistanceRequested=_gpsAssistanceRequested;
@property(nonatomic) _Bool wifiPowered; // @synthesize wifiPowered=_wifiPowered;
@property(nonatomic) int state; // @synthesize state=_state;
@property(copy, nonatomic) NSSet *pipelinedVenues; // @synthesize pipelinedVenues=_pipelinedVenues;
@property(nonatomic) int pipelinedSeeded; // @synthesize pipelinedSeeded=_pipelinedSeeded;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)clearAvailabilityTiles;
- (void)setAvailabilityTiles:(vector_bb831d88 *)arg1 withZScoreConfidenceInterval:(double)arg2;
- (vector_bb831d88 *)availabilityTiles;
- (_Bool)availabilityTilesLoaded;
- (void)setLastIndoorError:(optional_830905b6)arg1;
- (optional_830905b6 *)lastIndoorError;
- (void)setLatestPosition:(struct CLLastFix)arg1;
- (optional_72c1223f *)latestPosition;
- (void)setOutdoorEstimator:(struct CLOutdoorEstimator)arg1;
- (struct CLOutdoorEstimator *)outdoorEstimator;
- (id)init;

@end

