//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLLocationHarvesterProtocol.h"

@interface CLLocationHarvesterAdapter : CLIntersiloService <CLLocationHarvesterProtocol>
{
    struct CLLocationHarvester *_harvester;
}

+ (void)becameFatallyBlocked:(id)arg1;
+ (id)getSilo;
@property(nonatomic) struct CLLocationHarvester *harvester; // @synthesize harvester=_harvester;
- (void)shutdown;
- (void)setHarvestingEnabled:(_Bool)arg1;
- (void)setPrivateMode:(_Bool)arg1;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;

// Remaining properties
@property(nonatomic) _Bool valid;

@end

