//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEOTileKeyList;

@interface CLMapDataCacheHint : NSObject
{
    GEOTileKeyList *_tileKeys;
    int _policy;
    double _priority;
}

@property(nonatomic) double priority; // @synthesize priority=_priority;
@property(nonatomic) int policy; // @synthesize policy=_policy;
@property(retain, nonatomic) GEOTileKeyList *tileKeys; // @synthesize tileKeys=_tileKeys;
- (void)cacheTilesForCenter:(CDStruct_c3b9c2ee)arg1 radius:(double)arg2 forTileSetStyle:(int)arg3 atZoomLevel:(long long)arg4;

@end

