//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEOTileKeyList, NSMutableArray;

@interface CLMapDataSource : NSObject
{
    NSMutableArray *_cacheHints;
    NSMutableArray *_cache;
    GEOTileKeyList *_pending;
    _Bool _allowsNetworkUsage;
    int _travelDirectionBoth;
    int _travelDirectionPositive;
    int _travelDirectionNegative;
    int _travelDirectionInvalid;
    int _travelDirectionUnknown;
    int _mapMatchingTileSetStyle;
    long long _mapMatchingZoomLevel;
}

+ (id)sharedDataSource;
@property(readonly, nonatomic) int travelDirectionUnknown; // @synthesize travelDirectionUnknown=_travelDirectionUnknown;
@property(readonly, nonatomic) int travelDirectionInvalid; // @synthesize travelDirectionInvalid=_travelDirectionInvalid;
@property(readonly, nonatomic) int travelDirectionNegative; // @synthesize travelDirectionNegative=_travelDirectionNegative;
@property(readonly, nonatomic) int travelDirectionPositive; // @synthesize travelDirectionPositive=_travelDirectionPositive;
@property(readonly, nonatomic) int travelDirectionBoth; // @synthesize travelDirectionBoth=_travelDirectionBoth;
@property(nonatomic) _Bool allowsNetworkUsage; // @synthesize allowsNetworkUsage=_allowsNetworkUsage;
- (id)tileForKey:(struct _GEOTileKey *)arg1;
- (void)updateTileCache;
- (void)clearTileCache;
- (void)downloadTilesForKeys:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeAllCacheHints;
- (void)removeCacheHint:(id)arg1;
- (void)addCacheHint:(id)arg1;
- (id)multiPointFeaturesWithinDistance:(double)arg1 ofCoordinate:(CDStruct_c3b9c2ee)arg2 withCourse:(double)arg3 status:(int *)arg4;
@property(readonly, nonatomic) long long mapMatchingZoomLevel;
@property(readonly, nonatomic) int mapMatchingTileSetStyle;
- (void)openConnections;
- (void)closeConnections;
- (void)dealloc;
- (id)init;

@end

