//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLMapDataSource, GEOVectorTile;

@interface CLMapDataMultiPointFeature : NSObject
{
    GEOVectorTile *_tile;
    CDStruct_6cf27ba1 *_feature;
    unsigned long long _mapMatcherFeatureKey;
    _Bool _forward;
    double _offset;
    CLMapDataSource *_dataSource;
    struct CLDistanceCalc _distCalc;
    float _vertexCount;
    float *_vertexDistances;
    float _length;
}

- (id).cxx_construct;
- (CDStruct_88bbbd05)interpolateProjections:(const double *)arg1 count:(int)arg2 projectionOut:(double *)arg3;
- (CDStruct_88bbbd05)locationFixAtProjection:(double)arg1 forward:(_Bool)arg2;
- (void)roadsAtIntersectionFromOffset:(double)arg1 distance:(double)arg2 forward:(_Bool)arg3 next:(_Bool)arg4 outgoing:(id *)arg5 incoming:(id *)arg6 projectionOutput:(double *)arg7 distanceOutput:(double *)arg8 status:(int *)arg9;
- (float)_getVertexOffsetFromOffset:(double)arg1;
- (void)getCrossTileFeaturesAtOffset:(float)arg1 distance:(double)arg2 forward:(_Bool)arg3 next:(_Bool)arg4 outgoingFeatures:(id)arg5 incomingFeatures:(id)arg6 distanceOutput:(double *)arg7 status:(int *)arg8;
@property(readonly, nonatomic) _Bool isOnRoute;
@property(readonly, nonatomic) double offset;
@property(readonly, nonatomic) _Bool forward;
@property(readonly, nonatomic) _Bool isRailway;
@property(readonly, nonatomic) int formOfWay;
@property(readonly, nonatomic) int roadClass;
@property(readonly, nonatomic) int travelDirection;
@property(readonly, nonatomic) unsigned long long sectionCount;
@property(readonly, nonatomic) char *name;
@property(readonly, nonatomic) unsigned long long uniqueIdentifier;
- (id)description;
- (void)dealloc;
- (id)initWithFeature:(CDStruct_6cf27ba1 *)arg1 inTile:(id)arg2 atVertexOffset:(float)arg3 inDirection:(_Bool)arg4 fromDataSource:(id)arg5;
- (double)meterDistanceFromVertexOffset:(float)arg1 vertexDistance:(float)arg2;
- (void)_computeOffsetDistances:(float)arg1;
- (float)_distanceBetweenTilePointsInTile:(id)arg1 fromPoint:(CDStruct_b2fbf00d)arg2 toPoint:(CDStruct_b2fbf00d)arg3;

@end

