//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLIndoorDelegateProtocol.h"

@class CLIndoorMaintenance, CLIndoorPositionProvider, CLSilo, CLTimer, NSBundle, NSString;

@interface CLPipelineXPCBounce : NSObject <CLIndoorDelegateProtocol>
{
    struct CLPipelineLocationProvider *_provider;
    CLSilo *_silo;
    NSBundle *_indoorBundle;
    CLIndoorPositionProvider *_indoord;
    CLIndoorMaintenance *_daemonControl;
    CLTimer *_debounceTimer;
    CDUnknownBlockType _stopRequest;
}

@property(nonatomic) CDUnknownBlockType stopRequest; // @synthesize stopRequest=_stopRequest;
@property(retain, nonatomic) CLTimer *debounceTimer; // @synthesize debounceTimer=_debounceTimer;
@property(retain, nonatomic) CLIndoorMaintenance *daemonControl; // @synthesize daemonControl=_daemonControl;
@property(retain, nonatomic) CLIndoorPositionProvider *indoord; // @synthesize indoord=_indoord;
@property(retain, nonatomic) NSBundle *indoorBundle; // @synthesize indoorBundle=_indoorBundle;
@property(readonly, nonatomic) CLSilo *silo; // @synthesize silo=_silo;
@property(readonly, nonatomic) struct CLPipelineLocationProvider *provider; // @synthesize provider=_provider;
- (void)indoorDidUpdateToLocation:(id)arg1 fromLocation:(id)arg2;
- (void)indoorAssetDownloadProgress:(float)arg1;
- (void)indoorGivesUpWithLocation:(id)arg1;
- (void)indoorIsUncertainWithLocation:(id)arg1;
- (void)indoorDidFailWithError:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithProvider:(struct CLPipelineLocationProvider *)arg1 onSilo:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

