//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLQmiDmsManagerProtocol.h"

@interface CLQmiDmsManagerAdapter : CLIntersiloService <CLQmiDmsManagerProtocol>
{
    struct CLQmiDmsManager *_manager;
}

+ (void)becameFatallyBlocked:(id)arg1;
+ (id)getSilo;
@property(nonatomic) struct CLQmiDmsManager *manager; // @synthesize manager=_manager;
- (void)releaseClient;
- (void)enablePingTimer:(_Bool)arg1;
- (void)stop;
- (void)start;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;

// Remaining properties
@property(nonatomic) _Bool valid;

@end

