//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WPDeviceScannerDelegate.h"
#import "WPZoneTrackerDelegate.h"
#import "WirelessProximityDelegate.h"

@class NSMutableDictionary, NSRecursiveLock, NSString, WPDeviceScanner, WPZoneTracker, WirelessProximity;

@interface CLWPBridge : NSObject <WirelessProximityDelegate, WPDeviceScannerDelegate, WPZoneTrackerDelegate>
{
    NSRecursiveLock *_instanceLock;
    WirelessProximity *_proximity;
    long long _state;
    WPDeviceScanner *_scanner;
    WPZoneTracker *_tracker;
    NSMutableDictionary *_zonesAndHandlers;
    int _wpPowerState;
    CDUnknownBlockType _stateHandler;
    CDUnknownBlockType _updateHandler;
}

@property int wpPowerState; // @synthesize wpPowerState=_wpPowerState;
@property(copy, nonatomic) CDUnknownBlockType updateHandler; // @synthesize updateHandler=_updateHandler;
@property(copy, nonatomic) CDUnknownBlockType stateHandler; // @synthesize stateHandler=_stateHandler;
- (void)updateState;
- (void)zoneTracker:(id)arg1 didFailToRegisterZones:(id)arg2 withError:(id)arg3;
- (void)zoneTracker:(id)arg1 exitedZone:(id)arg2;
- (void)zoneTracker:(id)arg1 enteredZone:(id)arg2;
- (void)zoneTrackerDidUpdateState:(id)arg1;
- (void)_didTransitionZoneWithData:(id)arg1 state:(long long)arg2;
- (void)stopTrackingZones;
- (void)stopTrackingZone:(id)arg1;
- (_Bool)startTrackingZone:(id)arg1 forStates:(long long)arg2 transitionHandler:(CDUnknownBlockType)arg3;
- (void)scanner:(id)arg1 didFailToRegisterDevices:(id)arg2 withError:(id)arg3;
- (void)scanner:(id)arg1 foundDevice:(id)arg2 withData:(id)arg3;
- (void)deviceScannerDidUpdateState:(id)arg1;
- (void)stopScan;
- (void)startScanForBeaconTypes:(long long)arg1 updateHandler:(CDUnknownBlockType)arg2;
- (void)wirelessProximity:(id)arg1 didChangePowerState:(int)arg2;
- (void)unregisterForStateUpdates;
- (void)registerForStateUpdates:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithQueue:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

